spring:
  datasource:
    url: jdbc:mysql://192.168.247.130:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&&useSSL=false
    username: app
    password: 123456
  cache:
    type: SIMPLE
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl